nav:
  - ğŸ¡ ä¸»é¡µ: # ä¸»é¡µ/
    - index.md
    - å…³äºæˆ‘ğŸ‘¨â€ğŸ“: about.md
    - æ–°è®ºæ–‡å®£ä¼ ğŸ”¥:
      - 01.(ACM MM2024)å¦‚ä½•è®©å¤§è¯­è¨€æ¨¡å‹æ›´å¥½åœ°å®ŒæˆçŸ¥è¯†æ¨ç†: Mypapers/01-å¦‚ä½•è®©å¤§è¯­è¨€æ¨¡å‹æ›´å¥½åœ°å®ŒæˆçŸ¥è¯†æ¨ç†.md
      - 02.(ACL2024)å¤§è¯­è¨€æ¨¡å‹çš„çŸ¥è¯†åå¥½å¯¹é½: Mypapers/02-å¤§è¯­è¨€æ¨¡å‹çš„çŸ¥è¯†åå¥½å¯¹é½.md
      - 03.(COLING2024)ä¸å¹³è¡¡åœºæ™¯ä¸‹çš„å¤šæ¨¡æ€çŸ¥è¯†å›¾è°±è¡¥å…¨ : Mypapers/03-ä¸å¹³è¡¡åœºæ™¯ä¸‹çš„å¤šæ¨¡æ€çŸ¥è¯†å›¾è°±è¡¥å…¨.md
      - 04.(SIGIR2024)å¤æ‚åœºæ™¯ä¸‹çš„å¤šæ¨¡æ€çŸ¥è¯†å›¾è°±è¡¥å…¨ : Mypapers/04-å¤æ‚åœºæ™¯ä¸‹çš„å¤šæ¨¡æ€çŸ¥è¯†å›¾è°±è¡¥å…¨.md
      - 05.(AAAI2025)åŸºäºæ¨¡æ€åˆ†è¯çš„ç»†ç²’åº¦å®ä½“è¡¨ç¤ºå­¦ä¹ æ¡†æ¶ : Mypapers/05-åŸºäºæ¨¡æ€åˆ†è¯çš„ç»†ç²’åº¦å®ä½“è¡¨ç¤ºå­¦ä¹ æ¡†æ¶.md
  - ğŸ¦” æ¦‚ç‡å›¾/å› æœæ¨æ–­:
    - æ¦‚ç‡å›¾æ¨¡å‹:
      - PGM/index.md
      - 01. Introduction: PGM/CMU10-708PGM01ï¼šIntroduction.md
      - 02. Directed Graph Model: PGM/CMU10-708PGM02ï¼šGM.md
      - 03. Exact Inference: PGM/CMU10-708PGM03ï¼šExact Inference.md
    - å› æœæ¨æ–­:
      - Causality/index.md
      - Causality01-å› æœæ¨æ–­ä¸æ½œåœ¨ç»“æœæ¡†æ¶: Causality/Causality01-PotentialOutcome.md
      - Causality02-æ½œåœ¨ç»“æœæ¡†æ¶çš„åŸºæœ¬å‡è®¾: Causality/Causality02-Assumptions.md
      - Causality03-å› æœå›¾æ¨¡å‹: Causality/Causality03-CausalGraph.md
      - Causality04-åé—¨è°ƒæ•´: Causality/Causality04-Intervention&BackdoorAdjustment.md
      - Causality05-ç»“æ„å› æœæ¨¡å‹: Causality/Causality05-StructuralCausalModel.md
  - ğŸ•Šï¸ æœºå™¨å­¦ä¹ /æ·±åº¦å­¦ä¹ :
    - ğŸ¯ æœºå™¨å­¦ä¹ ä¸æ•°æ®æŒ–æ˜:
      - ML/index.md
      - ç»Ÿè®¡æœºå™¨å­¦ä¹ :
        - 01ï¼šæœºå™¨å­¦ä¹ ä¸­çš„åŸºæœ¬æ¦‚å¿µ: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 01ï¼šæœºå™¨å­¦ä¹ ä¸­çš„åŸºæœ¬æ¦‚å¿µ.md 
        - 02ï¼šè´å¶æ–¯å®šç†: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 02ï¼šè´å¶æ–¯å®šç†.md
        - 03ï¼šçº¿æ€§æ¨¡å‹: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 03ï¼šçº¿æ€§æ¨¡å‹.md
        - 04ï¼šæ„ŸçŸ¥æœº: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 04ï¼šæ„ŸçŸ¥æœº.md
        - 05ï¼šæ”¯æŒå‘é‡æœºSVM: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 05ï¼šæ”¯æŒå‘é‡æœºSVM.md
        - 06ï¼škNN: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 06ï¼škNN.md
        - 07ï¼šå†³ç­–æ ‘DecisionTree: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 07ï¼šå†³ç­–æ ‘DecisionTree.md
        - 08ï¼šèšç±»Clustering: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 08ï¼šèšç±»Clustering.md
        - 09ï¼šæå‡Boostingä¸Ensemble: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 09ï¼šæå‡Boostingä¸Ensemble.md
        - 10ï¼šEMç®—æ³•å’ŒGMM: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 10ï¼šEMç®—æ³•å’ŒGMM.md
        - 11ï¼šä¸»æˆåˆ†åˆ†æPCA: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 11ï¼šä¸»æˆåˆ†åˆ†æPCA.md
        - 12ï¼šçº¿æ€§åˆ¤åˆ«åˆ†æLDA: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 12ï¼šçº¿æ€§åˆ¤åˆ«åˆ†æLDA.md
        - 13ï¼šéšé©¬å°”å¯å¤«æ¨¡å‹: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 13ï¼šéšé©¬å°”å¯å¤«æ¨¡å‹.md
      - CS246-æ•°æ®æŒ–æ˜è¯¾ç¨‹ç¬”è®°:
        - ML/CS246/Lecture001.é¢‘ç¹æ¨¡å¼å’Œå…³è”è§„åˆ™æŒ–æ˜.md
        - ML/CS246/Lecture002.å±€éƒ¨æ•æ„Ÿæ€§å“ˆå¸Œ.md
        - ML/CS246/Lecture003.èšç±»å’Œé™ç»´.md
        - ML/CS246/Lecture004.æ¨èç³»ç»ŸRecSys.md
        - ML/CS246/Lecture005.æ•°æ®æµæŒ–æ˜.md
        - ML/CS246/Lecture006.è®¡ç®—å¹¿å‘Šå­¦.md
    - ğŸ° æ·±åº¦å­¦ä¹ :
      - CS231N/index.md
      - CS231N-ç¥ç»ç½‘ç»œä¸æ·±åº¦å­¦ä¹ :
        - 01.kNNå’Œçº¿æ€§åˆ†ç±»å™¨: CS231N/Stanford-CS231N-Assignmentæœ­è®°1ï¼škNNå’Œçº¿æ€§åˆ†ç±»å™¨.md
        - 02.å¤šå±‚å…¨è¿æ¥ç¥ç»ç½‘ç»œå’Œä¼˜åŒ–å™¨: CS231N/Stanford-CS231N-Assignmentæœ­è®°2ï¼šå¤šå±‚å…¨è¿æ¥ç¥ç»ç½‘ç»œå’Œä¼˜åŒ–å™¨.md
        - 03.Normalizationå’ŒDropOut: CS231N/Stanford-CS231N-Assignmentæœ­è®°3ï¼šNormalizationå’ŒDropOut.md
        - 04.å·ç§¯ç¥ç»ç½‘ç»œCNN: CS231N/Stanford-CS231N-Assignmentæœ­è®°4ï¼šå·ç§¯ç¥ç»ç½‘ç»œCNN.md
        - 05.RNN&LSTMä¸å›¾ç‰‡æè¿°: CS231N/Stanford-CS231N-Assignmentæœ­è®°5ï¼šRNN&LSTMä¸å›¾ç‰‡æè¿°.md
        - 06.Transformerä¸å›¾ç‰‡æè¿°: CS231N/Stanford-CS231N-Assignmentæœ­è®°6ï¼šTransformerä¸å›¾ç‰‡æè¿°.md
        - 07.æ¨¡å‹å¯è§†åŒ–ï¼Œå›¾åƒæ¬ºè¯ˆå’ŒGAN: CS231N/Stanford-CS231N-Assignmentæœ­è®°7ï¼šæ¨¡å‹å¯è§†åŒ–ï¼Œå›¾åƒæ¬ºè¯ˆå’ŒGAN.md
        - 08.è‡ªç›‘ç£å­¦ä¹ ä¸è¯¾ç¨‹æ€»ç»“: CS231N/Stanford-CS231N-Assignmentæœ­è®°8ï¼šè‡ªç›‘ç£å­¦ä¹ ä¸è¯¾ç¨‹æ€»ç»“.md
      - CS224W-å›¾æœºå™¨å­¦ä¹ ä¸å›¾ç¥ç»ç½‘ç»œ:
        - CS224W/index.md
        - 01.å¯¼è®ºï¼Œä¼ ç»Ÿçš„å›¾å­¦ä¹ æ–¹æ³• : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 01.md
        - 02.èŠ‚ç‚¹åµŒå…¥å’ŒPageRank : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 02.md
        - 03.æ¶ˆæ¯ä¼ é€’æœºåˆ¶ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 03.md
        - 04.å›¾ç¥ç»ç½‘ç»œåŸºç¡€ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 04.md
        - 05.å›¾ç¥ç»ç½‘ç»œçš„è®­ç»ƒå’Œåº”ç”¨ï¼Œè¡¨ç¤ºèƒ½åŠ›åˆ†æ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 05.md
        - 06.çŸ¥è¯†å›¾è°±ï¼ŒçŸ¥è¯†å›¾è°±æ¨ç† : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 06.md
        - 07.é¢‘ç¹å­å›¾æŒ–æ˜ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 07.md
        - 08.ç¤¾åŒºæ£€æµ‹ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 08.md
        - 09.å›¾ç”Ÿæˆæ¨¡å‹ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 09.md
        - 10.å›¾ç¥ç»ç½‘ç»œå‰æ²¿è¯é¢˜ : CS224W/CS224W-å›¾æœºå™¨å­¦ä¹ 10.md
      - CS224N-åŸºäºæ·±åº¦å­¦ä¹ çš„è‡ªç„¶è¯­è¨€å¤„ç†:
        - CS224N/index.md
        - 01-Introduction&WordVector: CS224N/NLP01-Introduction&WordVector.md
        - 02-Word2Vec: CS224N/NLP02-Word2Vec.md
        - 03-DependenceParsing: CS224N/NLP03-DependenceParsing.md
        - 04-LM&RNN&LSTM: CS224N/NLP04-LM&RNN&LSTM.md
        - 05-Seq2Seq: CS224N/NLP05-Seq2Seq.md
        - Assignment1&2: CS224N/Stanford-CS224N-Assignment1&2.md
        - Assignment3: CS224N/Stanford-CS224N-Assignment3.md
        - Assignment4: CS224N/Stanford-CS224N-Assignment4.md
    - ğŸ è®ºæ–‡é˜…è¯»:
      - Papers-old/index.md
      - æ—©æœŸè®ºæ–‡é˜…è¯»:
        # - Papers-old/index.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°01ï¼šçŸ¥è¯†å›¾è°±åµŒå…¥ç»¼è¿°.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°02ï¼šå…³ç³»æŠ½å–æ–‡çŒ®ç»¼è¿°.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°03ï¼šTransformer.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°04ï¼šNode2Vec.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°05ï¼šTransE.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°06ï¼šTransH.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°07ï¼šGraphVQA.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°08ï¼šRotatE.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°09ï¼šGAN4KGE&KBGAN.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°10ï¼šAffinityDependentNS.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°11ï¼šStructureAwareNS.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°12ï¼šPNS.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°13ï¼šNSCaching.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°14ï¼šçŸ¥è¯†å›¾è°±è·¯å¾„æ¨ç†.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°15ï¼šGraphTransformer.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°16ï¼šBERT.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°17ï¼šRule-Based-KGE.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°18ï¼šç¥ç»ç¬¦å·æ¨ç†å’ŒçŸ¥è¯†å›¾è°±.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°19ï¼šç”µå•†çŸ¥è¯†å›¾è°±é¢„è®­ç»ƒ.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°20ï¼šPathCon.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°21ï¼šFSL4TKG.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°22ï¼šKG-BERT&K-BERT.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°23ï¼šGraphformer.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°24ï¼šå¤šæ¨¡æ€çŸ¥è¯†å›¾è°±è¡¨ç¤ºå­¦ä¹ .md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°25ï¼šSMOREå¤§è§„æ¨¡çŸ¥è¯†å›¾è°±ç³»ç»Ÿ.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°26ï¼šK3Må¤šæ¨¡æ€å•†å“çŸ¥è¯†å›¾è°±é¢„è®­ç»ƒ.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°27ï¼šå›¾å¯¹æ¯”å­¦ä¹ .md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°28ï¼šå¤šæ¨¡æ€BERT.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°29ï¼šå¼‚æ„GCN.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°30ï¼šå¼‚æ„åˆ†å¸ƒå¼æœºå™¨å­¦ä¹ Partial Reduce.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°31ï¼šå¤§è§„æ¨¡çŸ¥è¯†å›¾è°±å¯¹é½LargeEA.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°32ï¼šPrompt.md
        - Papers-old/è®ºæ–‡é˜…è¯»ç¬”è®°33ï¼šç»“åˆBERTçš„çŸ¥è¯†å›¾è°±è¡¥å…¨.md
      - 01-GANä¸å¯¹æ¯”å­¦ä¹ çš„è®¾è®¡: Papers/01-GANä¸å¯¹æ¯”å­¦ä¹ çš„è®¾è®¡.md
      - 02-VAEä¸CVAEçš„åŸºæœ¬æ¶æ„: Papers/02-VAEä¸CVAEçš„åŸºæœ¬æ¶æ„.md
      - 03-å¤šæ¨¡æ€ç‰¹å¾çš„èåˆä¸æå–: Papers/03-å¤šæ¨¡æ€ç‰¹å¾çš„èåˆä¸æå–.md
      - 04-å› æœæ³¨æ„åŠ›æœºåˆ¶: Papers/04-å› æœæ³¨æ„åŠ›æœºåˆ¶.md
      - 05-å¤§è¯­è¨€æ¨¡å‹: Papers/05-å¤§è¯­è¨€æ¨¡å‹LLM.md
      - 06-å¤§è¯­è¨€æ¨¡å‹å¯¹é½: Papers/06-å¤§æ¨¡å‹Alignment.md
      - 07-ä»¥æ•°æ®ä¸ºä¸­å¿ƒçš„AI: Papers/07-ä»¥æ•°æ®ä¸ºä¸­å¿ƒçš„AI.md
      - 08-çŸ¥è¯†å›¾è°±é¢„è®­ç»ƒ: Papers/08-çŸ¥è¯†å›¾è°±é¢„è®­ç»ƒ.md
  - ğŸ¦ƒï¸ æ•°æ®ç»“æ„/ç®—æ³•:
    - DS/index.md
    - æ•°æ®ç»“æ„åŸºç¡€: DS/ds.md
    - é«˜çº§æ•°æ®ç»“æ„ä¸ç®—æ³•åˆ†æ: DS/ads.md
    - ğŸLeetCodeåˆ·é¢˜è®°å½•:
      - æ•°ç»„: Leetcode/Array.md
      - å­—ç¬¦ä¸²: Leetcode/String.md
      - æ ˆ: Leetcode/Stack.md
      - é“¾è¡¨: Leetcode/Linklist.md
      - å †: Leetcode/Heap.md
      - åŠ¨æ€è§„åˆ’: Leetcode/DP.md
      - å‰ç¼€å’Œ: Leetcode/Prefix.md
      - å›æº¯: Leetcode/Backtrack.md
      - æ·±åº¦ä¼˜å…ˆæœç´¢: Leetcode/DFS.md
      - åŒæŒ‡é’ˆ: Leetcode/TwoPointers.md
      - è´ªå¿ƒ: Leetcode/DFS.md
      - æ ‘: Leetcode/Tree.md
      - æ»‘åŠ¨çª—å£: Leetcode/Windows.md
      - ä½è¿ç®—: Leetcode/Bit.md
      - è„‘ç­‹æ€¥è½¬å¼¯: Leetcode/Trick.md
  - ğŸŠ ç¼–ç¨‹è¯­è¨€:
    - PL/index.md
    - C++:
      - OOPè¯¾ç¨‹ç¬”è®°: PL/CPP/OOP-Review.md
    - Java:
      - PL/Java/Javaåº”ç”¨æŠ€æœ¯1ï¼šåŸºç¡€è¯­æ³•.md
      - PL/Java/Javaåº”ç”¨æŠ€æœ¯2ï¼šç±»å’Œå¯¹è±¡.md
      - PL/Java/Javaåº”ç”¨æŠ€æœ¯3ï¼šé«˜çº§è¯­æ³•ç‰¹æ€§.md
      - PL/Java/æ·±å…¥ç†è§£JVM-1.md
    - Go:
      - PL/Go/Go-01. Goè¯­è¨€çš„åŸºç¡€è¯­æ³•.md
      - PL/Go/Go-02. Goè¯­è¨€çš„ä¾èµ–ç®¡ç†ä¸è¿›é˜¶è¯­æ³•.md
  - ğŸ¦– è®¡ç®—æœºç³»ç»Ÿ:
    - ğŸ‘è®¡ç®—æœºç³»ç»ŸåŸç†:
      - System/index.md
      - System/00-intro.md
      - System/01-mips.md
      - System/02-calculation.md
      - System/03-cpu.md
      - System/04-memory.md
      - System/05-io.md
    - ğŸ’ æ“ä½œç³»ç»Ÿ:
      - OS/index.md
      - OS/æ“ä½œç³»ç»Ÿ0-Linuxå†…æ ¸.md
      - OS/æ“ä½œç³»ç»Ÿ1-å¯¼è®º.md
      - OS/æ“ä½œç³»ç»Ÿ2-è¿›ç¨‹&çº¿ç¨‹.md
      - OS/æ“ä½œç³»ç»Ÿ3-CPUè°ƒåº¦&åŒæ­¥.md
      - OS/æ“ä½œç³»ç»Ÿ4-åŒæ­¥å’Œæ­»é”.md
      - OS/æ“ä½œç³»ç»Ÿ5-å­˜å‚¨.md
      - OS/æ“ä½œç³»ç»Ÿ6-æ–‡ä»¶.md
      - OS/æ“ä½œç³»ç»Ÿ7-ç£ç›˜å’ŒIO.md
    - ğŸ“ è®¡ç®—æœºç½‘ç»œ:
      - Networking/index.md
      - è®¡ç®—æœºç½‘ç»œ1-OSIæ¨¡å‹: Networking/è®¡ç®—æœºç½‘ç»œ1-OSIæ¨¡å‹.md
      - è®¡ç®—æœºç½‘ç»œ2-ç‰©ç†å±‚:  Networking/è®¡ç®—æœºç½‘ç»œ2-ç‰©ç†å±‚.md
      - è®¡ç®—æœºç½‘ç»œ3-æ•°æ®é“¾è·¯å±‚&MAC: Networking/è®¡ç®—æœºç½‘ç»œ3-æ•°æ®é“¾è·¯å±‚&MAC.md
      - è®¡ç®—æœºç½‘ç»œ4-ç½‘ç»œå±‚: Networking/è®¡ç®—æœºç½‘ç»œ4-ç½‘ç»œå±‚.md
      - è®¡ç®—æœºç½‘ç»œ5-è¿è¾“å±‚: Networking/è®¡ç®—æœºç½‘ç»œ5-è¿è¾“å±‚.md
      - è®¡ç®—æœºç½‘ç»œ6-åº”ç”¨å±‚: Networking/è®¡ç®—æœºç½‘ç»œ6-åº”ç”¨å±‚.md
      - è®¡ç®—æœºç½‘ç»œ7-ç½‘ç»œå®‰å…¨: Networking/è®¡ç®—æœºç½‘ç»œ7-ç½‘ç»œå®‰å…¨.md
    - ğŸ¶ æ•°æ®åº“ç³»ç»Ÿ:
      - DB/index.md
      - ZJUæ•°æ®åº“ç³»ç»Ÿè¯¾ç¨‹å¤ä¹ ç¬”è®°: DB/db.md
      - CMU15-445 Database Systems:
        - DB/CMU15-445/index.md
        - DB/CMU15-445/CMU15-445-01-æ•°æ®å­˜å‚¨.md
        - DB/CMU15-445/CMU15-445-02-ç´¢å¼•.md
        - DB/CMU15-445/CMU15-445-03-æŸ¥è¯¢å¤„ç†.md
        - DB/CMU15-445/CMU15-445-04-æŸ¥è¯¢ä¼˜åŒ–.md
        - DB/CMU15-445/CMU15-445-05-äº‹åŠ¡ä¸å¹¶å‘æ§åˆ¶.md
      - MIT6.830 Database Systems Project:
        - DB/MIT6.830/MIT6.830-lab1-SimpleDB Overview.md
        - DB/MIT6.830/MIT6.830-lab2-SimpleDB Operators.md
        - DB/MIT6.830/MIT6.830-lab3-Query Optimizer.md
        - DB/MIT6.830/MIT6.830-lab4-Transaction.md
    - CSCI300:
      - CSCI300/Lecture1-Overview.md
      - CSCI300/Lecture2-DataInMemory.md
  - ğŸ³ æ‚è°ˆä¸æ€»ç»“:
    - Gossip/index.md
    - I. 2021å¹´åº¦æ€»ç»“: Gossip/2021å¹´åº¦æ€»ç»“.md
    - II. æœ¬ç§‘å‰ä¸‰å¹´çš„æ€»ç»“: Gossip/æœ¬ç§‘å‰ä¸‰å¹´çš„æ€»ç»“.md
    - III. å¯¹è½¯å·¥ä¸“ä¸šçš„è¯¾ç¨‹è¯„ä»·å’Œä¿®æ”¹æ„è§: Gossip/å¯¹è½¯å·¥ä¸“ä¸šçš„è¯¾ç¨‹è¯„ä»·å’Œä¿®æ”¹æ„è§.md
    - IV. PythonåŠ©æ•™ä½“éªŒ: Gossip/PythonåŠ©æ•™ä½“éªŒ.md
    - V. 2022å¹´åº¦æ€»ç»“: Gossip/2022å¹´åº¦æ€»ç»“.md
    - VI. å†™åœ¨è¯»ç ”ä¸€å¹´ä¹‹é™…: Gossip/å†™åœ¨è¯»ç ”ä¸€å¹´ä¹‹é™….md
    - VII. 2023å¹´åº¦æ€»ç»“: Gossip/2023å¹´åº¦æ€»ç»“.md
    - VIII. 2024å¹´åº¦æ€»ç»“: Gossip/2024å¹´åº¦æ€»ç»“.md
  - ğŸŒ¾ å®ä¹ ä¸æ‰¾å·¥:
    - Jobs/index.md
    - 2021æ˜¥æ‹›:
      - 2021æ˜¥æ‹›é˜¿é‡Œäº‘ä¸å­—èŠ‚æ•™è‚²éƒ¨é—¨é¢ç»: Jobs/2021spring/intern.md
      - é¢è¯•å‡†å¤‡:
        - MySQLçŸ¥è¯†æ•´ç†: Jobs/2021spring/intern1.md
        - è®¾è®¡æ¨¡å¼: Jobs/2021spring/intern2.md
        - Javaè¯­æ³•: Jobs/2021spring/intern3.md
        - æ“ä½œç³»ç»Ÿä¸è®¡ç®—æœºç½‘ç»œ: Jobs/2021spring/intern4.md
    - 2024å¹´æš‘æœŸå®ä¹ åº”è˜è®°å½•: Jobs/2024spring/2024å¹´æš‘æœŸå®ä¹ åº”è˜è®°å½•.md

    #  Leetcode

site_name: å°è§’é¾™çš„å­¦ä¹ è®°å½•
site_url: https://zhang-each.github.io/My-CS-notebook/
repo_name: Zhang-Each/My-CS-notebook
repo_url: https://github.com/zhang-each/My-CS-notebook/

theme:
  name: material
  features:
    - navigation.tabs # ä¸€çº§å¯¼èˆªåœ¨æ¨ªç€çš„å¯¼èˆªæ 
    - content.code.annotate # å¯ä»¥åœ¨ä»£ç å—ä¸­å¢æ·»ç‚¹å‡»å±•ç¤ºçš„æ³¨é‡Šï¼Œå‚è§ https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.indexes # å°† index é¡µé¢ç›´æ¥é™„åˆ°å°èŠ‚åä¸Š
    - navigation.top # å›åˆ°é¡¶éƒ¨æŒ‰é’®
    # - navigation.sections # äºŒçº§å¯¼èˆªæ˜¯ç²—ä½“
    # - navigation.expand # å¯¼èˆªé»˜è®¤å±•å¼€
    - toc.follow # toc è·Ÿéš
    # - toc.integrate # æ–‡æ¡£ toc é›†æˆåˆ°æ€»ç›®å½•ä¸­ 
  language: 'zh'
  palette:
    primary: black
    scheme: default
  font:
    text: Noto Serif SC # Comic Sans MS # Palatino
    code: Roboto Mono
  custom_dir: overrides # ç”¨æ¥æè¯„è®ºçš„ï¼Œå‚è€ƒ https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/


markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: underscore
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
copyright: 'æœ¬é¡µé¢çš„å…¨éƒ¨å†…å®¹åœ¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> å’Œ <a href="https://github.com/zTrix/sata-license">SATA</a> åè®®ä¹‹æ¡æ¬¾ä¸‹æä¾›ï¼Œé™„åŠ æ¡æ¬¾äº¦å¯èƒ½åº”ç”¨ã€‚'

extra_css:
  - 'from_oi_wiki/css/extra.css?v=13'
  - css/status.css

extra_javascript:
  - 'from_oi_wiki/js/extra.js'
  # - js/mathjax.js # æ”¯æŒæ•°å­¦å…¬å¼ï¼Œref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # æ”¯æŒè¡¨æ ¼æ’åº
  # - js/tablesort.js
  - //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
  - statistics
