nav:
  - ğŸ¡ ä¸»é¡µ: # ä¸»é¡µ/
    - index.md
    - å…³äºæˆ‘: about.md
  - ğŸ¯ ç»Ÿè®¡æœºå™¨å­¦ä¹ :
    - ML/index.md
    - 01ï¼šæœºå™¨å­¦ä¹ ä¸­çš„åŸºæœ¬æ¦‚å¿µ: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 01ï¼šæœºå™¨å­¦ä¹ ä¸­çš„åŸºæœ¬æ¦‚å¿µ.md 
    - 02ï¼šè´å¶æ–¯å®šç†: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 02ï¼šè´å¶æ–¯å®šç†.md
    - 03ï¼šçº¿æ€§æ¨¡å‹: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 03ï¼šçº¿æ€§æ¨¡å‹.md
    - 04ï¼šæ„ŸçŸ¥æœº: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 04ï¼šæ„ŸçŸ¥æœº.md
    - 05ï¼šæ”¯æŒå‘é‡æœºSVM: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 05ï¼šæ”¯æŒå‘é‡æœºSVM.md
    - 06ï¼škNN: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 06ï¼škNN.md
    - 07ï¼šå†³ç­–æ ‘DecisionTree: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 07ï¼šå†³ç­–æ ‘DecisionTree.md
    - 08ï¼šèšç±»Clustering: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 08ï¼šèšç±»Clustering.md
    - 09ï¼šæå‡Boostingä¸Ensemble: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 09ï¼šæå‡Boostingä¸Ensemble.md
    - 10ï¼šEMç®—æ³•å’ŒGMM: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 10ï¼šEMç®—æ³•å’ŒGMM.md
    - 11ï¼šä¸»æˆåˆ†åˆ†æPCA: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 11ï¼šä¸»æˆåˆ†åˆ†æPCA.md
    - 12ï¼šçº¿æ€§åˆ¤åˆ«åˆ†æLDA: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 12ï¼šçº¿æ€§åˆ¤åˆ«åˆ†æLDA.md
    - 13ï¼šéšé©¬å°”å¯å¤«æ¨¡å‹: ML/ç»Ÿè®¡æœºå™¨å­¦ä¹ 13ï¼šéšé©¬å°”å¯å¤«æ¨¡å‹.md
  - ğŸ° æ·±åº¦å­¦ä¹ :
    - CS231N/index.md
    - CS231N-ç¥ç»ç½‘ç»œä¸æ·±åº¦å­¦ä¹ :
      - 01.kNNå’Œçº¿æ€§åˆ†ç±»å™¨: CS231N/Stanford-CS231N-Assignmentæœ­è®°1ï¼škNNå’Œçº¿æ€§åˆ†ç±»å™¨.md
      - 02.å¤šå±‚å…¨è¿æ¥ç¥ç»ç½‘ç»œå’Œä¼˜åŒ–å™¨: CS231N/Stanford-CS231N-Assignmentæœ­è®°2ï¼šå¤šå±‚å…¨è¿æ¥ç¥ç»ç½‘ç»œå’Œä¼˜åŒ–å™¨.md
      - 03.Normalizationå’ŒDropOut: CS231N/Stanford-CS231N-Assignmentæœ­è®°3ï¼šNormalizationå’ŒDropOut.md
      - 04.å·ç§¯ç¥ç»ç½‘ç»œCNN: CS231N/Stanford-CS231N-Assignmentæœ­è®°4ï¼šå·ç§¯ç¥ç»ç½‘ç»œCNN.md
      - 05.RNN&LSTMä¸å›¾ç‰‡æè¿°: CS231N/Stanford-CS231N-Assignmentæœ­è®°5ï¼šRNN&LSTMä¸å›¾ç‰‡æè¿°.md
      - 06.Transformerä¸å›¾ç‰‡æè¿°: CS231N/Stanford-CS231N-Assignmentæœ­è®°6ï¼šTransformerä¸å›¾ç‰‡æè¿°.md
      - 07.æ¨¡å‹å¯è§†åŒ–ï¼Œå›¾åƒæ¬ºè¯ˆå’ŒGAN: CS231N/Stanford-CS231N-Assignmentæœ­è®°7ï¼šæ¨¡å‹å¯è§†åŒ–ï¼Œå›¾åƒæ¬ºè¯ˆå’ŒGAN.md
      - 08.è‡ªç›‘ç£å­¦ä¹ ä¸è¯¾ç¨‹æ€»ç»“: CS231N/Stanford-CS231N-Assignmentæœ­è®°8ï¼šè‡ªç›‘ç£å­¦ä¹ ä¸è¯¾ç¨‹æ€»ç»“.md
    - CS224W-å›¾æœºå™¨å­¦ä¹ ä¸å›¾ç¥ç»ç½‘ç»œ:
      - CS224W/index.md
      - 01.å¯¼è®ºï¼Œä¼ ç»Ÿçš„å›¾å­¦ä¹ æ–¹æ³• : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 01.md
      - 02.èŠ‚ç‚¹åµŒå…¥å’ŒPageRank : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 02.md
      - 03.æ¶ˆæ¯ä¼ é€’æœºåˆ¶ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 03.md
      - 04.å›¾ç¥ç»ç½‘ç»œåŸºç¡€ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 04.md
      - 05.å›¾ç¥ç»ç½‘ç»œçš„è®­ç»ƒå’Œåº”ç”¨ï¼Œè¡¨ç¤ºèƒ½åŠ›åˆ†æ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 05.md
      - 06.çŸ¥è¯†å›¾è°±ï¼ŒçŸ¥è¯†å›¾è°±æ¨ç† : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 06.md
      - 07.é¢‘ç¹å­å›¾æŒ–æ˜ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 07.md
      - 08.ç¤¾åŒºæ£€æµ‹ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 08.md
      - 09.å›¾ç”Ÿæˆæ¨¡å‹ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 09.md
      - 10.å›¾ç¥ç»ç½‘ç»œå‰æ²¿è¯é¢˜ : CS224W/CS224Wï¼šå›¾æœºå™¨å­¦ä¹ 10.md
    - CS224N-åŸºäºæ·±åº¦å­¦ä¹ çš„è‡ªç„¶è¯­è¨€å¤„ç†:
      - CS224N/index.md
      - 01-Introduction&WordVector: CS224N/NLP01-Introduction&WordVector.md
      - 02-Word2Vec: CS224N/NLP02-Word2Vec.md
      - 03-DependenceParsing: CS224N/NLP03-DependenceParsing.md
      - 04-LM&RNN&LSTM: CS224N/NLP04-LM&RNN&LSTM.md
      - 05-Seq2Seq: CS224N/NLP05-Seq2Seq.md
      - Assignment1&2: CS224N/Stanford-CS224N-Assignment1&2.md
      - Assignment3: CS224N/Stanford-CS224N-Assignment3.md
      - Assignment4: CS224N/Stanford-CS224N-Assignment4.md
  - ğŸ‘ è®¡ç®—æœºç³»ç»Ÿ:
    - System/index.md
    - System/00-intro.md
    - System/01-mips.md
    - System/02-calculation.md
    - System/03-cpu.md
    - System/04-memory.md
    - System/05-io.md
  - ğŸ’ æ“ä½œç³»ç»Ÿ:
    - OS/index.md
    - OS/æ“ä½œç³»ç»Ÿ0-Linuxå†…æ ¸.md
    - OS/æ“ä½œç³»ç»Ÿ1-å¯¼è®º.md
    - OS/æ“ä½œç³»ç»Ÿ2-è¿›ç¨‹&çº¿ç¨‹.md
    - OS/æ“ä½œç³»ç»Ÿ3-CPUè°ƒåº¦&åŒæ­¥.md
    - OS/æ“ä½œç³»ç»Ÿ4-åŒæ­¥å’Œæ­»é”.md
    - OS/æ“ä½œç³»ç»Ÿ5-å­˜å‚¨.md
    - OS/æ“ä½œç³»ç»Ÿ6-æ–‡ä»¶.md
    - OS/æ“ä½œç³»ç»Ÿ7-ç£ç›˜å’ŒIO.md
  - ğŸ“ è®¡ç®—æœºç½‘ç»œ:
    - Networking/index.md
    - è®¡ç®—æœºç½‘ç»œ1-OSIæ¨¡å‹: Networking/è®¡ç®—æœºç½‘ç»œ1-OSIæ¨¡å‹.md
    - è®¡ç®—æœºç½‘ç»œ2-ç‰©ç†å±‚:  Networking/è®¡ç®—æœºç½‘ç»œ2-ç‰©ç†å±‚.md
    - è®¡ç®—æœºç½‘ç»œ3-æ•°æ®é“¾è·¯å±‚&MAC: Networking/è®¡ç®—æœºç½‘ç»œ3-æ•°æ®é“¾è·¯å±‚&MAC.md
    - è®¡ç®—æœºç½‘ç»œ4-ç½‘ç»œå±‚: Networking/è®¡ç®—æœºç½‘ç»œ4-ç½‘ç»œå±‚.md
    - è®¡ç®—æœºç½‘ç»œ5-è¿è¾“å±‚: Networking/è®¡ç®—æœºç½‘ç»œ5-è¿è¾“å±‚.md
    - è®¡ç®—æœºç½‘ç»œ6-åº”ç”¨å±‚: Networking/è®¡ç®—æœºç½‘ç»œ6-åº”ç”¨å±‚.md
    - è®¡ç®—æœºç½‘ç»œ7-ç½‘ç»œå®‰å…¨: Networking/è®¡ç®—æœºç½‘ç»œ7-ç½‘ç»œå®‰å…¨.md
  - ğŸ¶ æ•°æ®åº“ç³»ç»Ÿ:
    - DB/index.md
    - æ•°æ®åº“ç³»ç»Ÿå¤ä¹ ç¬”è®°: DB/db.md
  - ğŸ· æ‚è°ˆä¸æ€»ç»“:
    - æ‚è°ˆä¸æ€»ç»“/index.md
    - I. 2021å¹´åº¦æ€»ç»“: æ‚è°ˆä¸æ€»ç»“/2021å¹´åº¦æ€»ç»“.md
    - II. æœ¬ç§‘å‰ä¸‰å¹´çš„æ€»ç»“: æ‚è°ˆä¸æ€»ç»“/æœ¬ç§‘å‰ä¸‰å¹´çš„æ€»ç»“.md
    - III. å¯¹è½¯å·¥ä¸“ä¸šçš„è¯¾ç¨‹è¯„ä»·å’Œä¿®æ”¹æ„è§: æ‚è°ˆä¸æ€»ç»“/å¯¹è½¯å·¥ä¸“ä¸šçš„è¯¾ç¨‹è¯„ä»·å’Œä¿®æ”¹æ„è§.md
    - IV. 2022å¹´åº¦æ€»ç»“: æ‚è°ˆä¸æ€»ç»“/2022å¹´åº¦æ€»ç»“.md

site_name: å°è§’é¾™çš„å­¦ä¹ è®°å½•
site_url: https://zhang-each.github.io/My-CS-notebook/
repo_name: Zhang-Each/My-CS-notebook
repo_url: https://github.com/zhang-each/My-CS-notebook/

theme:
  name: material
  features:
    - navigation.tabs # ä¸€çº§å¯¼èˆªåœ¨æ¨ªç€çš„å¯¼èˆªæ 
    - content.code.annotate # å¯ä»¥åœ¨ä»£ç å—ä¸­å¢æ·»ç‚¹å‡»å±•ç¤ºçš„æ³¨é‡Šï¼Œå‚è§ https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # åœ°å€æ ä¸­çš„ URL ä¼šéšå½“å‰ä½ç½®å˜åŒ–ä¸ºå¯¹åº”å°èŠ‚çš„ URL
    - navigation.indexes # å°† index é¡µé¢ç›´æ¥é™„åˆ°å°èŠ‚åä¸Š
    - navigation.top # å›åˆ°é¡¶éƒ¨æŒ‰é’®
    # - navigation.sections # äºŒçº§å¯¼èˆªæ˜¯ç²—ä½“
    # - navigation.expand # å¯¼èˆªé»˜è®¤å±•å¼€
    - toc.follow # toc è·Ÿéš
    # - toc.integrate # æ–‡æ¡£ toc é›†æˆåˆ°æ€»ç›®å½•ä¸­ 
  language: 'zh'
  palette:
    primary: black
    scheme: default
  font:
    text: Hiragino Sans GB # Palatino
    code: Roboto Mono
  custom_dir: overrides # ç”¨æ¥æè¯„è®ºçš„ï¼Œå‚è€ƒ https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/


markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
copyright: 'æœ¬é¡µé¢çš„å…¨éƒ¨å†…å®¹åœ¨ <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> å’Œ <a href="https://github.com/zTrix/sata-license">SATA</a> åè®®ä¹‹æ¡æ¬¾ä¸‹æä¾›ï¼Œé™„åŠ æ¡æ¬¾äº¦å¯èƒ½åº”ç”¨ã€‚<br /><span id="busuanzi_container_site_uv">æœ¬ç«™è®¿å®¢æ€»äººæ•°<span id="busuanzi_value_site_uv"></span>äººæ¬¡ï¼Œ</span><span id="busuanzi_container_site_pv">æœ¬ç«™æ€»è®¿é—®æ¬¡æ•°<span id="busuanzi_value_site_pv"></span>æ¬¡ã€‚</span>'

extra_css:
  - 'from_oi_wiki/css/extra.css?v=13'
  - css/status.css

extra_javascript:
  - 'from_oi_wiki/js/extra.js'
  # - js/mathjax.js # æ”¯æŒæ•°å­¦å…¬å¼ï¼Œref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # æ”¯æŒè¡¨æ ¼æ’åº
  # - js/tablesort.js
  - //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
  # - statistics
